default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: detect-aws-credentials

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '2.3.56' # change to tag or sha
    hooks:
    - id: checkov
      verbose: true
      args: [--soft-fail]